language: python
branches:
  only:
    - master
script:
    - echo 'start'
    - '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && ./version.sh'
    - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash ./version.sh; fi'
